---
title: "GCI Impact on OpenFaaS - SDPROJ"
author: 
- "David Ferreira Quaresma (david.quaresma@ccc.ufcg.edu.br)"
- "Paulo Felipe Feitosa (paulofelipe.feitosa@gmail.com)"
date: "november, 2019"
output: pdf_document
---

# GCI vs NOGCI
```{r echo=FALSE, results='hide', message=FALSE}
source("functions.R")
get_data <- function(expid, case) {
  data = filter(read.al(paste("../experiment/results", expid, "/listfiller-", case, "1.csv", sep="")), status == 200)
  for (i in 2:10) {
    data = rbind(data, filter(read.al(paste("../experiment/results", expid, "/listfiller-", case, as.character(i), ".csv", sep="")), status == 200))
  }
  data$latency = data$latency * 1000
  return (data)
}
gci = get_data("", "gci")
nogci = get_data("", "nogci")
gci_nocoldstart   = filter(  gci, body > 0)
nogci_nocoldstart = filter(nogci, body > 0)
```

#### ECDF for response time (with coldstart)
```{r  fig.width=15, fig.height=5, echo=FALSE}
graph_tail(gci$latency, nogci$latency, title="THUMBNAILATOR ECDF LATENCY - p0 to p100", x_limit_inf=0, x_limit_sup=300)
graph_tail(gci$latency, nogci$latency, title="THUMBNAILATOR ECDF LATENCY - p0 to p95", x_limit_inf=3, x_limit_sup=10)
graph_tail(gci$latency, nogci$latency, title="THUMBNAILATOR ECDF LATENCY - p95 to p100", x_limit_inf=10, x_limit_sup=50)
```

#### ECDF for response time (no coldstart)
```{r  fig.width=15, fig.height=5, echo=FALSE}
graph_tail(gci_nocoldstart$latency, nogci_nocoldstart$latency, title="THUMBNAILATOR ECDF LATENCY - p0 to p100", x_limit_inf=0, x_limit_sup=300)
graph_tail(gci_nocoldstart$latency, nogci_nocoldstart$latency, title="THUMBNAILATOR ECDF LATENCY - p0 to p95", x_limit_inf=3, x_limit_sup=10)
graph_tail(gci_nocoldstart$latency, nogci_nocoldstart$latency, title="THUMBNAILATOR ECDF LATENCY - p95 to p100", x_limit_inf=10, x_limit_sup=50)
```

#### summary table of confidence interval for response time, both in milliseconds (with coldstart)
```{r  fig.width=15, fig.height=5, echo=FALSE}
summary_table(gci$latency, "gci", nogci$latency, "nogci")
```

#### summary table of confidence interval for response time, both in milliseconds (no Coldstart)
```{r  fig.width=15, fig.height=5, echo=FALSE}
summary_table(gci_nocoldstart$latency, "gci", nogci_nocoldstart$latency, "nogci")
```
